#if !canImport(ObjectiveC)
import XCTest

extension BootstringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BootstringTests = [
        ("testPunycodeDecoding", testPunycodeDecoding),
        ("testPunycodeEncoding", testPunycodeEncoding),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BootstringTests.__allTests__BootstringTests),
    ]
}
#endif
